language: node_js
node_js:
  - '11.8.0'
cache:
  yarn: true
  directories:
    - node_modules
script:
  - npm run build-gh
env:
  - GH_PAGES=true
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  github-url: github.ibm.com
  on:
    branch: master